"""Launch variables — GPU-specific environment files."""

import os


def generate_launch_vars_nvidia(wineprefix: str) -> None:
    """Write NVIDIA launch_vars.env inside the WINEPREFIX."""
    dest = os.path.join(wineprefix, "launch_vars.env")
    content = (
        "# Bellum Launch Variables (NVIDIA)\n"
        "# Auto-generated by Bellum Linux Installer\n"
        "\n"
        'export __GAMESCOPE_INTEGRATION=""\n'
        'export __GAMESCOPE_INTEGRATION_FORCE="0"\n'
        'export __GAMESCOPE_INTEGRATION_GAMER_MODE="0"\n'
        'export NVAPI_OVERRIDE_CONFIG=""\n'
        'export NVVM_LIBDIR="${PROTONPATH}/nvvm/lib64"\n'
        'export LD_LIBRARY_PATH="${PROTONPATH}/lib64:${LD_LIBRARY_PATH:-}"\n'
    )
    with open(dest, "w") as fh:
        fh.write(content)


def generate_launch_vars_amd(wineprefix: str, is_fsr41: bool) -> None:
    """Write AMD launch_vars.env inside the WINEPREFIX."""
    dest = os.path.join(wineprefix, "launch_vars.env")
    fsr4 = "4.1.0" if is_fsr41 else "1"
    content = (
        "# Bellum Launch Variables (AMD)\n"
        "# Auto-generated by Bellum Linux Installer\n"
        "\n"
        'export __GAMESCOPE_INTEGRATION=""\n'
        'export __GAMESCOPE_INTEGRATION_FORCE="0"\n'
        'export __GAMESCOPE_INTEGRATION_GAMER_MODE="0"\n'
        'export NVAPI_OVERRIDE_CONFIG=""\n'
        'export NVVM_LIBDIR="${PROTONPATH}/nvvm/lib64"\n'
        'export LD_LIBRARY_PATH="${PROTONPATH}/lib64:${LD_LIBRARY_PATH:-}"\n'
        f'export FSR4_UPGRADE="{fsr4}"\n'
        f'export FSR4_RDNA3_UPGRADE="{fsr4}"\n'
    )
    with open(dest, "w") as fh:
        fh.write(content)


def generate_launch_vars_file(wineprefix: str, gpu_type: str, is_fsr41: bool = False) -> None:
    """Dispatch to the correct GPU-specific generator."""
    if gpu_type == "NVIDIA":
        generate_launch_vars_nvidia(wineprefix)
    elif gpu_type == "AMD":
        generate_launch_vars_amd(wineprefix, is_fsr41)
