"""Launcher wrapper scripts — GPU-specific bash wrappers for ~/.local/bin/Bellum."""

import os

from tuxbellum.config.paths import path_mgr
from tuxbellum.core.logging import Logger

_TAIL_NAME = "Bellum"


def generate_launcher_wrapper(
    wineprefix: str,
    proton_path: str,
    gpu_type: str,
    logger: Logger,
) -> None:
    """Create ~/.local/bin/Bellum with GPU-specific content."""
    launcher_exe = os.path.join(
        wineprefix,
        "drive_c/users/steamuser/AppData/Local/"
        "Astarte Industries/Astarte Launcher/AstarteLauncher.exe",
    )
    proton_bin = os.path.join(proton_path, "proton")

    script = _build_script(wineprefix, launcher_exe, proton_bin, gpu_type)
    _write_system_bin(script, logger)


def _build_script(
    wineprefix: str,
    launcher_exe: str,
    proton_bin: str,
    gpu_type: str,
) -> str:
    common_header = (
        "#!/bin/bash\n"
        "# Bellum Launcher Wrapper\n"
        "# Auto-generated by the Bellum Linux Installer\n\n"
        "set -u\n\n"
        f'LAUNCH_VARS="{wineprefix}/launch_vars.env"\n'
        f'GAME_DIR="{wineprefix}"\n'
        f'export WINEPREFIX="{wineprefix}"\n'
        f'LAUNCHER_EXE="{launcher_exe}"\n'
        f'PROTON_BIN="{proton_bin}"\n'
        'export PROTONPATH="$(dirname "$PROTON_BIN")"\n\n'
        "load_launch_vars() {\n"
        '    if [ -f "$LAUNCH_VARS" ]; then\n'
        "        set -a\n"
        '        source "$LAUNCH_VARS"\n'
        "        set +a\n"
        "    else\n"
        '        echo "ERROR: Launch variables file not found: $LAUNCH_VARS" >&2\n'
        "        exit 1\n"
        "    fi\n"
        "}\n\n"
        "validate_paths() {\n"
        '    if [ ! -f "$LAUNCHER_EXE" ]; then\n'
        '        echo "ERROR: Launcher executable not found: $LAUNCHER_EXE" >&2\n'
        "        exit 1\n"
        "    fi\n\n"
        "    if ! command -v wine &>/dev/null; then\n"
        '        echo "ERROR: wine not found or not executable" >&2\n'
        "        exit 1\n"
        "    fi\n"
        "}\n\n"
        "run_launcher() {\n"
        '    cd "$GAME_DIR" || exit 1\n'
        '    LOG_FILE="$GAME_DIR/launcher.log"\n\n'
        '    wineboot "--restart"\n'
        "    sleep 1\n\n"
        '    wine "$LAUNCHER_EXE" "$@" > "$LOG_FILE" 2>> "$LOG_FILE"\n\n'
        '    wineboot "--end-session"\n\n'
        '    return "$?"\n'
        "}\n\n"
        "main() {\n"
        "    load_launch_vars\n"
        "    validate_paths\n"
        '    run_launcher "$@"\n'
        "    exit $?\n"
        "}\n\n"
        'main "$@"\n'
    )
    return common_header


def _write_system_bin(content: str, logger: Logger) -> None:
    target = os.path.join(path_mgr.user_local_bin(), _TAIL_NAME)
    os.makedirs(os.path.dirname(target), exist_ok=True)
    os.makedirs(path_mgr.user_local_bin(), exist_ok=True)

    with open(target, "w") as fh:
        fh.write(content)
    os.chmod(target, 0o755)
    logger.info(f"[OK] Launcher written: {target}")
