"""Launcher wrapper scripts — GPU-specific bash wrappers for /usr/local/bin/Bellum."""

import os
import tempfile

from tuxbellum.core.system import run_command, RunMode
from tuxbellum.core.logging import Logger


_TAIL_NAME = "Bellum"


def generate_launcher_wrapper(
    wineprefix: str,
    proton_path: str,
    gpu_type: str,
    logger: Logger,
) -> None:
    """Create /usr/local/bin/Bellum with GPU-specific content."""
    launcher_exe = os.path.join(
        wineprefix,
        "drive_c/users/steamuser/AppData/Local/"
        "Astarte Industries/Astarte Launcher/AstarteLauncher.exe",
    )
    proton_bin = os.path.join(proton_path, "proton")

    script = _build_script(wineprefix, launcher_exe, proton_bin, gpu_type)
    _write_system_bin(script, logger)


def _build_script(
    wineprefix: str,
    launcher_exe: str,
    proton_bin: str,
    gpu_type: str,
) -> str:
    common_header = (
        "#!/bin/bash\n"
        "# Bellum Launcher Wrapper\n"
        "# Auto-generated by the Bellum Linux Installer\n\n"
        "set -u\n\n"
        f'LAUNCH_VARS="{wineprefix}/launch_vars.env"\n'
        f'GAME_DIR="{wineprefix}"\n'
        f'export WINEPREFIX="{wineprefix}"\n'
        f'LAUNCHER_EXE="{launcher_exe}"\n'
        f'PROTON_BIN="{proton_bin}"\n'
        'export PROTONPATH="$(dirname "$PROTON_BIN")"\n\n'
        "load_launch_vars() {\n"
        '    if [ -f "$LAUNCH_VARS" ]; then\n'
        "        set -a\n"
        '        source "$LAUNCH_VARS"\n'
        "        set +a\n"
        "    else\n"
        '        echo "ERROR: Launch variables file not found: $LAUNCH_VARS" >&2\n'
        "        exit 1\n"
        "    fi\n"
        "}\n\n"
        "validate_paths() {\n"
        '    if [ ! -f "$LAUNCHER_EXE" ]; then\n'
        '        echo "ERROR: Launcher executable not found: $LAUNCHER_EXE" >&2\n'
        "        exit 1\n"
        "    fi\n\n"
        '    if [ ! -x "$PROTON_BIN" ]; then\n'
        '        echo "ERROR: $PROTON_BIN not found or not executable" >&2\n'
        "        exit 1\n"
        "    fi\n"
        "}\n\n"
        "run_launcher() {\n"
        '    cd "$GAME_DIR" || exit 1\n'
        '    LOG_FILE="$GAME_DIR/launcher.log"\n\n'
        '    wineboot "--end-session"\n'
        "    sleep 1\n\n"
        '    export GAMEID="bellum"\n'
        '    umu-run "$LAUNCHER_EXE" "$@" > "$LOG_FILE" 2>> "$LOG_FILE"\n\n'
        '    return "$?"\n'
        "}\n\n"
        "main() {\n"
        "    load_launch_vars\n"
        "    validate_paths\n"
        '    run_launcher "$@"\n'
        "    exit $?\n"
        "}\n\n"
        'main "$@"\n'
    )
    return common_header


def _write_system_bin(content: str, logger: Logger) -> None:
    target = f"/usr/local/bin/{_TAIL_NAME}"
    os.makedirs(os.path.dirname(target), exist_ok=True)

    if os.geteuid() != 0:
        _write_via_pkexec(content, target, logger)
    else:
        with open(target, "w") as fh:
            fh.write(content)
        os.chmod(target, 0o755)


def _write_via_pkexec(content: str, target: str, logger: Logger) -> None:
    fd, tmp = tempfile.mkstemp(prefix="bellum-launcher-", suffix=".sh")
    try:
        os.write(fd, content.encode())
        os.close(fd)

        run_command(RunMode.STREAM, ["pkexec", "cp", tmp, target])
        run_command(RunMode.STREAM, ["pkexec", "chmod", "755", target])

        import getpass
        user = getpass.getuser()
        run_command(RunMode.STREAM, ["pkexec", "chown", f"{user}:{user}", target])
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass
